const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const read = (relPath) => fs.readFileSync(path.join(ROOT, relPath), 'utf8');
const exists = (relPath) => fs.existsSync(path.join(ROOT, relPath));

test('phase4 orchestrator files and App wiring exist', () => {
  assert.equal(exists('orchestrators/chatWorkspaceOrchestrator.ts'), true);
  assert.equal(exists('orchestrators/signalWorkspaceOrchestrator.ts'), true);
  assert.equal(exists('orchestrators/tradeLockerWorkspaceOrchestrator.ts'), true);
  assert.equal(exists('hooks/orchestrators/useChatWorkspaceOrchestrator.ts'), true);
  assert.equal(exists('hooks/orchestrators/useSignalWorkspaceOrchestrator.ts'), true);
  assert.equal(exists('hooks/orchestrators/useTradeLockerWorkspaceOrchestrator.ts'), true);
  assert.equal(exists('components/app/AppShell.tsx'), true);
  assert.equal(exists('components/app/AppOrchestrator.tsx'), true);
  assert.equal(exists('components/app/AppShellContent.tsx'), true);
  assert.equal(exists('components/app/AppSidebarPanels.tsx'), true);
  assert.equal(exists('components/app/AppOutsideShellContent.tsx'), true);
  assert.equal(exists('components/app/models.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildChatPanelModel.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildSignalPanelModel.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildTradeLockerPanelModel.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildShellContentModel.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildOutsideShellModel.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildSidebarPanelsModel.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildSidebarLegacyPanelModel.ts'), true);
  assert.equal(exists('orchestrators/app/builders/buildAppOrchestratorDeps.ts'), true);

  const app = read('App.tsx');
  const appShell = read('components/app/AppShell.tsx');
  const appOrchestrator = read('components/app/AppOrchestrator.tsx');
  const appShellContent = read('components/app/AppShellContent.tsx');
  const appSidebarPanels = read('components/app/AppSidebarPanels.tsx');
  const appOutsideShellContent = read('components/app/AppOutsideShellContent.tsx');
  assert.equal(app.includes("useChatWorkspaceOrchestrator"), true);
  assert.equal(app.includes("useSignalWorkspaceOrchestrator"), true);
  assert.equal(app.includes("useTradeLockerWorkspaceOrchestrator"), true);
  assert.equal(app.includes("useChatWorkspaceOrchestrator(chatWorkspaceOrchestratorOptions)"), true);
  assert.equal(app.includes("useSignalWorkspaceOrchestrator(signalWorkspaceOrchestratorOptions)"), true);
  assert.equal(app.includes("useTradeLockerWorkspaceOrchestrator(tradeLockerWorkspaceOrchestratorOptions)"), true);
  assert.equal(app.includes("import AppShell from './components/app/AppShell';"), false);
  assert.equal(app.includes("import AppOrchestrator from './components/app/AppOrchestrator';"), true);
  assert.equal(app.includes('<AppOrchestrator'), true);
  assert.equal(app.includes('const appOrchestratorDeps = buildAppOrchestratorDeps({'), true);
  assert.equal(app.includes('deps={appOrchestratorDeps}'), true);
  assert.equal(app.includes('buildSidebarPanelsModel({'), true);
  assert.equal(app.includes('buildSidebarLegacyPanelModel({'), true);
  assert.equal(app.includes('buildShellContentModel({'), true);
  assert.equal(app.includes('buildOutsideShellModel({'), true);
  assert.equal(appShell.includes('export interface AppShellProps {'), true);
  assert.equal(appShell.includes('overlaySlot?: React.ReactNode;'), true);
  assert.equal(appShell.includes('chromeSlot?: React.ReactNode;'), true);
  assert.equal(appShell.includes('mainSlot?: React.ReactNode;'), true);
  assert.equal(appOrchestrator.includes('export interface AppOrchestratorDeps {'), true);
  assert.equal(appOrchestrator.includes('<ErrorBoundary onError={onError}>'), true);
  assert.equal(appOrchestrator.includes('<AppShell isFullscreen={shell.isFullscreen}'), true);
  assert.equal(appOrchestrator.includes('<AppShellContent ctx={{ ...shell, sidebarPanels }} />'), true);
  assert.equal(appOrchestrator.includes('<AppOutsideShellContent ctx={outsideShell} />'), true);
  assert.equal(appShellContent.includes('<AppSidebarPanels model={sidebarPanels} />'), true);
  assert.equal(appSidebarPanels.includes('<React.Suspense fallback={SIDEBAR_LAZY_FALLBACK}>'), true);
  assert.equal(appOutsideShellContent.includes('<OnboardingGate'), true);
  assert.equal(appOutsideShellContent.includes('<SettingsModal'), true);
});
