/* eslint-disable */
// Auto-generated by scripts/generateIpcContract.cjs. Do not edit manually.

export const IPC_CONTRACT = {
  "version": 1,
  "generatedBy": "scripts/generateIpcContract.cjs",
  "channels": [
    {
      "name": "agentRunner:cancel",
      "domain": "agentRunner",
      "scopes": [
        "agentRunner"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "agentRunner:evaluateSignal",
      "domain": "agentRunner",
      "scopes": [
        "agentRunner"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "agentRunner:status",
      "domain": "agentRunner",
      "scopes": [
        "agentRunner"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "app:shutdown-ready",
      "domain": "app",
      "scopes": [
        "bridge"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "broker:getActive",
      "domain": "broker",
      "scopes": [
        "broker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "broker:list",
      "domain": "broker",
      "scopes": [
        "broker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "broker:request",
      "domain": "broker",
      "scopes": [
        "broker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "broker:setActive",
      "domain": "broker",
      "scopes": [
        "broker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "calendar:getEvents",
      "domain": "calendar",
      "scopes": [
        "calendar"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "codebase:listFiles",
      "domain": "codebase",
      "scopes": [
        "codebase"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "codebase:readFile",
      "domain": "codebase",
      "scopes": [
        "codebase"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "codebase:search",
      "domain": "codebase",
      "scopes": [
        "codebase"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "codebase:traceDataflow",
      "domain": "codebase",
      "scopes": [
        "codebase"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "diagnostics:getAppMeta",
      "domain": "diagnostics",
      "scopes": [
        "diagnostics"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "diagnostics:getBundleStats",
      "domain": "diagnostics",
      "scopes": [
        "diagnostics"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "diagnostics:getMainLog",
      "domain": "diagnostics",
      "scopes": [
        "diagnostics"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "diagnostics:listReleases",
      "domain": "diagnostics",
      "scopes": [
        "diagnostics"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "diagnostics:runtimeStream:start",
      "domain": "diagnostics",
      "scopes": [
        "diagnostics"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "diagnostics:runtimeStream:stop",
      "domain": "diagnostics",
      "scopes": [
        "diagnostics"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "gemini:tts",
      "domain": "gemini",
      "scopes": [
        "gemini"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "glass:captureNativeSnapshot",
      "domain": "glass",
      "scopes": [
        "capture"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "glass:captureWebContents",
      "domain": "glass",
      "scopes": [
        "capture"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "glass:saveUserFile",
      "domain": "glass",
      "scopes": [
        "file"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "mt5Bridge:openLog",
      "domain": "mt5Bridge",
      "scopes": [
        "mt5"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "mt5Bridge:start",
      "domain": "mt5Bridge",
      "scopes": [
        "mt5"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "mt5Bridge:status",
      "domain": "mt5Bridge",
      "scopes": [
        "mt5"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "news:getSnapshot",
      "domain": "news",
      "scopes": [
        "news"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "openai:images",
      "domain": "openai",
      "scopes": [
        "openai"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "openai:responses",
      "domain": "openai",
      "scopes": [
        "openai"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "openai:responsesStream",
      "domain": "openai",
      "scopes": [
        "openai"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "runtime_ops:controller_state:update",
      "domain": "runtime_ops",
      "scopes": [
        "bridge"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "runtime_ops:external_command:result",
      "domain": "runtime_ops",
      "scopes": [
        "bridge"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "runtime_ops:external_command:subscribe",
      "domain": "runtime_ops",
      "scopes": [
        "bridge"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "runtime_ops:external_command:unsubscribe",
      "domain": "runtime_ops",
      "scopes": [
        "bridge"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "runtime_ops:renderer_event",
      "domain": "runtime_ops",
      "scopes": [
        "bridge"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "secrets:clearGeminiKey",
      "domain": "secrets",
      "scopes": [
        "secrets"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "secrets:clearOpenAIKey",
      "domain": "secrets",
      "scopes": [
        "secrets"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "secrets:getGeminiKey",
      "domain": "secrets",
      "scopes": [],
      "inMain": true,
      "inPreload": false
    },
    {
      "name": "secrets:getOpenAIKey",
      "domain": "secrets",
      "scopes": [
        "secrets"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "secrets:getStatus",
      "domain": "secrets",
      "scopes": [
        "secrets"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "secrets:setGeminiKey",
      "domain": "secrets",
      "scopes": [
        "secrets"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "secrets:setOpenAIKey",
      "domain": "secrets",
      "scopes": [
        "secrets"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "telegram:answerCallback",
      "domain": "telegram",
      "scopes": [
        "telegram"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "telegram:sendMessage",
      "domain": "telegram",
      "scopes": [
        "telegram"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "telegram:sendPhoto",
      "domain": "telegram",
      "scopes": [
        "telegram"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "telegram:startPolling",
      "domain": "telegram",
      "scopes": [
        "telegram"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "telegram:stopPolling",
      "domain": "telegram",
      "scopes": [
        "telegram"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:addMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:append",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:appendResearchStep",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:archiveAgentMemories",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:clearAgentMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:clearMemories",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:createExperimentNote",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:createOptimizerWinner",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:createPlaybookRun",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:createResearchSession",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:deleteAgentMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:deleteMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:findRecent",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:flush",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:getAgentMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:getExperimentNote",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:getOptimizerEvalCache",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:getOptimizerWinner",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:getOptimizerWinnerBySessionRound",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:getPlaybookRun",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:getResearchSession",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:list",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listAgentMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listEvents",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listExperimentNotes",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listMemories",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listOptimizerWinners",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listPlaybookRuns",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listResearchSessions",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:listResearchSteps",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:pruneOptimizerEvalCache",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:putOptimizerEvalCache",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:reserve",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:stats",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:update",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:updateMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradeLedger:upsertAgentMemory",
      "domain": "tradeLedger",
      "scopes": [
        "tradeLedger"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:cancelAllOrders",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:cancelOrder",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:clearSavedSecrets",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:closePosition",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:connect",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:disconnect",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getAccountMetrics",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getAccounts",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getDailyBar",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getHistory",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getHistorySeries",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getInstrumentConstraints",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getInstrumentDetails",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getOrderDetails",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getOrders",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getOrdersHistory",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getPositionDetails",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getQuote",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getQuotes",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getRateLimitPolicy",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getSavedConfig",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getSessionDetails",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getSessionStatus",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getSnapshot",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:getStreamStatus",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:modifyOrder",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:modifyPosition",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:placeOrder",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:reconcileAccountState",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:searchInstruments",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:setActiveAccount",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:setRateLimitPolicy",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:setTradingOptions",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:startStream",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:status",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:stopStream",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "tradelocker:updateSavedConfig",
      "domain": "tradelocker",
      "scopes": [
        "tradelocker"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "window:getFullscreen",
      "domain": "window",
      "scopes": [
        "window"
      ],
      "inMain": true,
      "inPreload": true
    },
    {
      "name": "window:setFullscreen",
      "domain": "window",
      "scopes": [
        "window"
      ],
      "inMain": true,
      "inPreload": true
    }
  ],
  "allowedScopes": [
    "agentRunner",
    "bridge",
    "broker",
    "calendar",
    "capture",
    "clipboard",
    "codebase",
    "diagnostics",
    "file",
    "gemini",
    "live",
    "mt5",
    "news",
    "openai",
    "secrets",
    "telegram",
    "tradeLedger",
    "tradelocker",
    "window"
  ],
  "appBootScopes": [],
  "missingBootScopes": []
} as const;

export type IpcContract = typeof IPC_CONTRACT;
export type IpcChannel = IpcContract["channels"][number]["name"];
export type IpcScope = IpcContract["allowedScopes"][number];
